version: '3'

services:
  postgresdb:
    image: postgres:9.6.10
    command: postgres -c 'max_connections=300'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: generator
      PGDATA : /var/lib/postgresql/data
    volumes:
      - ../assets/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    external: true
    driver: overlay